# Generated by Django 4.2.6 on 2023-12-09 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_rede_ufpi', '0003_alter_mainpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
