# Generated by Django 4.2.6 on 2023-12-18 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_rede_ufpi', '0005_comunidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app_rede_ufpi.comunidades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
