# Generated by Django 5.0 on 2024-01-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rede_ufpi', '0008_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='comunidade',
        ),
    ]
