# Generated by Django 5.0 on 2024-01-24 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rede_ufpi', '0010_comentarioscomunidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioscomunidade',
            name='comunidade_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentscomu', to='app_rede_ufpi.comunidades'),
        ),
    ]
